### ISSUE TITLE
some additions (no github client access)

### ISSUE THREAD

**Issue by WainPetopia** [bloerwald/wow-listfile#102]
Update: added files via the link from Jarts below.

**Comment by Jarts37** [comment]
You should just use Marlamin website page for adding new lines
https://bnet.marlam.in/checkFiles.php

**Comment by WainPetopia** [comment]
Thanks :)  I forgot about that one.

**Comment by bloerwald** [comment]
There is no issue with just pasting them into an issue as you did as well. Somebody will take care of it either way ;)
