### ISSUE TITLE
possible incorrect files

### ISSUE THREAD

**Issue by WainPetopia** [bloerwald/wow-listfile#103]
I'm pretty sure these two files don't exist:
creature/bloodtickmount/bloodtickmountsaddle_green.blp
creature/bloodtickmount/bloodtickmountsaddle_purple.blp

I just submitted the correct ones via Marlamin's page. They're the same, but without the underscores, i.e.:
creature/bloodtickmount/bloodtickmountsaddlegreen.blp
creature/bloodtickmount/bloodtickmountsaddlepurple.blp

**Comment by Marlamin** [comment]
Removed in 33aa082e71ba0a0958d2908070500d5c32d074ae and pulled in with e0c114ea6558a76469da527c6a5ce5c46554c680, thanks!
