### ISSUE TITLE
HorseMultiSaddle saddle/armor textures

### ISSUE THREAD

**Issue by Smerdokryl** [bloerwald/wow-listfile#107]
Can't find them anywhere. Am I looking in the wrong places, or just too soon?

**Comment by bloerwald** [comment]
- what exactly are you looking for (I.e. where do you get „horsemultisaddle“ from)?
- where did you look

**Comment by Smerdokryl** [comment]
![image](https://user-images.githubusercontent.com/35412834/36220786-cc3e4c90-11b3-11e8-9214-89164a4e3afb.png)
![image](https://user-images.githubusercontent.com/35412834/36220859-10cd14a4-11b4-11e8-929c-6fcd7881024b.png)
It's the new horse model with various saddle geosets. Body textures are there, but not the saddles.

I've looked in various horse-related folders and searched the listfile for keywords like horse, saddle, armor, etc.

**Comment by bloerwald** [comment]
Entries of `CreatureDisplayInfo` with `modelID == 10638` will have the file data ids for the saddles in `textureVariation[1]` (or 0?).

**Comment by Smerdokryl** [comment]
But there is no FileData table
![image](https://user-images.githubusercontent.com/35412834/36222972-d9cb35c4-11ba-11e8-8b08-3b1681b46639.png)

**Comment by Smerdokryl** [comment]
How can I use the IDs then? Sorry, I'm really unfamiliar with the whole post-MoP file system

**Comment by bloerwald** [comment]
That depends on your CASC tool. It probably offers opening by id. 

For horsemultisaddle.m2, you can open by 
- file data id `1781898`
- filename `creature/horsemultisaddle/horsemultisaddle.m2`
- filename hash `9e471ab49c9180f8`
- content hash `a79964549ffd9dfe3c0489f919ca1a8a`

If your tool only allows opening by filename, it probably sucks.

**Comment by Smerdokryl** [comment]
Well, I'm using CASC Explorer, which, as far as I know, is the only tool available. And there is no "open certain file by name/id/whatever" exactly, it just opens everything for you to browse folders and stuff

**Comment by Marlamin** [comment]
From author of CASCExplorer:

21:47 <[TOM_RUS]> add name to listfile?
21:48 <[TOM_RUS]> or go to unknown folder and you should have filedata id here

The latter probably applies

**Comment by WainPetopia** [comment]
The skin files for that model exist, but as far as I know nobody has guessed their names yet. I've tried many, many millions of name combinations but I had no luck, others have done the same. If somebody knows the names then they're keeping it secret.

**Comment by bloerwald** [comment]
9255c3387e92ba0d16378d7059813d4dd03f2cd0
