### ISSUE TITLE
bad file names?

### ISSUE THREAD

**Issue by WainPetopia** [bloerwald/wow-listfile#108]
I noticed that a bunch of file names added in 135e96f that have 'draenor' in their names don't seem to exist in my database. I'm just curious if they're mistakes or for a different/old version of the game.

**Comment by justMaku** [comment]
Could you give me an example of such file?

**Comment by Marlamin** [comment]
Files like ```item/weapon/axe_1h_draenorraid_d_03violet.blp``` are no longer present in current builds but have been present in older builds. This file specifically looks to have been moved to its proper directory of ```item/objectcomponents/weapon/axe_1h_draenorraid_d_03violet.blp```. I'm assuming it is similar for other files.

**Comment by Marlamin** [comment]
Did a quick check, but my 6.0+ database already has over 100k filenames in it that have either been removed or have never been shipped. [Here's a CSV list of all the files no longer present in the latest 8.0.1 build](http://marlamin.com/u/removedfileslatest801.csv) (7MB). The listfile in repo has even more files that were removed before CASC was a thing. 

I'm thinking about making an addition to my listfile generator that optionally allows one to only download a listfile with files that actually exist in a specific build as that would probably significantly cut down loading times in some applications (including my own). Listfile in repo will likely always keep these files though.

**Comment by WainPetopia** [comment]
I see, thanks!  I know the listfile contains a lot of removed files but these caught my attention since they were only just added. Thanks for clarifying. 

It would be fantastic if we could grab a listfile that only contained current (or last few versions) files. WMV only supports recent builds anyway and it would cut the listfile down massively
