### ISSUE TITLE
Panthara sound files

### ISSUE THREAD

**Issue by redlocker35** [bloerwald/wow-listfile#87]
Hello,

Thank you very much for making an updated list file. However, I cannot find the path for any of the sounds associated with the new Panthara creatures and the Twilight StarSeeker mount which might share the sounds.

Thanks!

**Comment by Marlamin** [comment]
It's possible you can find the filenames on WoWhead, should be easier than
anything we can recommend.

**Comment by redlocker35** [comment]
Yes I can find the files on Wowhead, but I need the file path in order to replace them or make edits

**Comment by Marlamin** [comment]
Wowhead should list the filenames, I think? Do you have a link to the
creature/mount in question?

**Comment by redlocker35** [comment]
https://www.wowhead.com/npc=124303/duskcloak-panthara#sounds

**Comment by Marlamin** [comment]
These are currently unknown ogg files, it seems.

https://bnet.marlam.in/files.php#search=1561447&page=1

**Comment by redlocker35** [comment]
Specifically I was hoping to mute mon_panthara_mountspecial as it is a little loud, and when tamed the creatures yawn with this sound very often.

**Comment by bloerwald** [comment]
While good to know that we are missing files, I don't think someone is going to search for your specific missing ones, making this issue an issue that will never be closed. If you ever manage to find the sounds (they may in fact already been found with us just not knowing), feel free to reopen the issue with the names, or opening a merge request.
