### ISSUE TITLE
Missing music

### ISSUE THREAD

**Issue by Nezoak** [bloerwald/wow-listfile#88]
is the listfile not complete or is it missing some music from argus? i cant seen to find the xenedar walk music

**Comment by Marlamin** [comment]
Some Argus music is known, see last few pages @
https://bnet.marlam.in/files.php#search=type:mp3&page=1 but there's a good
chance someone hasn't figured out the filenames for the music yet, sadly.
This will occur more and more.

**Comment by Nezoak** [comment]
but eventually someone finds them right? or is there a way to find them? not sure how the wowhead/mmochamp people do it so fast

**Comment by hoxton22** [comment]
Mmochampion finds the mp3 files inside the CASC, and give them the name presents in the sound db2.

Finding the exact pathname of mp3 is really more complicated, sometimes the name is present in the file, sometime not.

**Comment by Marlamin** [comment]
You can probably find it on my site that I linked earlier as one of the
mp3s without a filename.

**Comment by Nezoak** [comment]
oh i see all the red ones one of those is the one im looking for probably but im unable to extract it until the file name appears right? >_<

**Comment by bloerwald** [comment]
You can extract them using the filedataid or on Alram's site using the link to the right?

**Comment by Nezoak** [comment]
awesome thanks guys i found them!

**Comment by hoxton22** [comment]
you can also open cascexplorer and search in the "unknown" folder

**Comment by bloerwald** [comment]
While good to know that we are missing files, I don't think someone is going to search for your specific missing ones, making this issue an issue that will never be closed. If you ever manage to find the sounds (they may in fact already been found with us just not knowing), feel free to reopen the issue with the names, or opening a merge request.
