### ISSUE TITLE
new file names

### ISSUE THREAD

**Issue by Konctantin** [bloerwald/wow-listfile#97]
world/wmo/draenor/nagrand/6ng_highmaul_stairs_ruins01_000_lod1.blp
world/wmo/draenor/nagrand/6ng_highmaul_stairs_ruins01_000_lod1_l.blp
world/wmo/draenor/nagrand/6ng_highmaul_stairs_ruins01_000_lod2.blp
world/wmo/draenor/nagrand/6ng_highmaul_stairs_ruins01_000_lod2_l.blp
world/wmo/pandaria/thunderisle/zandalari/zandalari_boat_large_000_lod1.blp
world/wmo/pandaria/thunderisle/zandalari/zandalari_boat_large_000_lod1_l.blp
world/wmo/pandaria/thunderisle/zandalari/zandalari_boat_large_000_lod2.blp
world/wmo/pandaria/thunderisle/zandalari/zandalari_boat_large_000_lod2_l.blp

**Comment by bloerwald** [comment]
apparently was already merged by some commit. thanks for your contribution!
